
exp_name: cifar10
seed: 2022

env_name: cifar10

params_exp:
    arch: [128,128]
    num_timesteps: 0.5e+6
    eval_interval: 2500

params_agents:

    'A2C':
        alg_type: A2C
        hyperparams: {learning_rate: 1.0e-4}
        batch_size: 32
    'DQN':
        alg_type: DQN
        hyperparams: {learning_rate: 5.0e-6}
        batch_size: 32
    'PPO':
        alg_type: PPO
        hyperparams: {learning_rate: 1.0e-4}
        batch_size: 32

