
exp_name: personalization
seed: 2022

env_name: personalization

params_exp:
    arch: [512,512]
    num_timesteps: 1.0e+5
    eval_interval: 500

params_agents:

    'A2C':
        alg_type: A2C
        hyperparams: {learning_rate: 1.0e-3}
        batch_size: 32
    'DQN':
        alg_type: DQN
        hyperparams: {learning_rate: 1.0e-3}
        batch_size: 32
    'PPO':
        alg_type: PPO
        hyperparams: {learning_rate: 1.0e-3}
        batch_size: 32

