exp_name: spotify
seed: 2024

env_name: spotify

params_exp:
    arch: [256,256]
    num_timesteps: 0.2e+5
    eval_interval: 100

params_agents:

    'A2C':
        alg_type: A2C
        hyperparams: {learning_rate: 1.0e-3}
        batch_size: 32
    'DQN':
        alg_type: DQN
        hyperparams: {learning_rate: 1.0e-3}
        batch_size: 32
    'PPO':
        alg_type: PPO
        hyperparams: {learning_rate: 1.0e-3}
        batch_size: 32

